language: java
dist: trusty

jdk:
- openjdk8

env:
  global:
  - secure: "jWkP4n5sl7VS+te68k874ZdmtXtJBbiNf0HiE/5UR4F8qb/C3oBtW7cZ4X75xDvhzn/UbDPXRk9upBAWUsk0upTCIxX7VIVVFgqB4dFq5zFHlZT+qyAwyoju/bBW3CDZvrlaDg0uitF7shI1oh5E6IcyNls1qQFs+mqTt24TwhjYHJEnwrnH6W7ds42ackHnAYgoguiBi48MlErxXIKej7/KuqGAEIa/fUDXbzyT7+ZAZ3qAqB5e5DgaOmyqsB0XHQEx0PDFiW/7rgO4NNdVbzrG/ybvLx664xrG5AgVnS8QcI2eC5r7hOZvGsHAa/krj3SUgtvXEK63rD9NH8+dUonAuIvuR2Rzasaozx6pzI22myJ6zoqz5suN7tm+dSSK4z17AjzAcEonPpHiFXmcF0SNmOovxBJ9rQxglZrzlnS3OTepqebUJV4ZijCOcKkrVmt2uLdlR0/iugUZ5LUKqL/aaUOy86Xbh8kXPvJxEOA1ScXJXzhr3EeE/H4otiXVMybvDfBxTbpaalJL7boNN4BLu2t0ZjUcN2mPOfv91cWLGzr21fvYPM3SoG7dhkIDy3zFlP8zfpYU0i8XWSKDXqTEAH7wgjwXW2QjNq1XdHLhFFAD2C2XiGXDG7jz8pZhnrJbjoXBAdJ8eQpsCuwnE5556dYAvC94JXCWAVHWe/I="
  - secure: "kyuogV09iWQWHoVKMAyecBdO2mQCgyUzF1o1bpYECucJYZuWTud8oxfzlo7d0mw9JM9Wgw7lfeihMYux321T72RSRhQOf4XIRSNIbkFjHJYE0mn42YpE1rD8EHD3rEdHUfuN75oGxhA4kd6NbtFf2gOYujWCtG9NEqlbSbFM6xsYlYw4b4qqPdMMFAn41p9nIZokZ9oYZwURBe4sCx9M+UEdY9b4AP6tKQFF4VJJTyO+3QfWpDKVliJeZkNyxk3/aH7140ABfVOgsTaA9sDMg5IdW73oH8g7GH10f0umjqszkLVwGKz1K6F396qDfrXFD+8KAyV+CYerJHSAWmDbRosfZT5sC9zNbVTmr2Js1WtpbTuLyeLfd9P3STayuHyggTwJjnmkZ6J/ZDf79WsBxwxMga6WywyBoxVziB+Y7nky3vxNnio/+xIre56H5GO1LyOoa8hocD2+IU4fuRjI4PpyWXuDUjnvyTPW/pPfliGK0+83vGSg6HbwN+hVJ9+xPz6mGmVZwDTHgKLDcagnhEguOIs3ARaeRUhWLLGqI99KkCFsQHYdacSyNy33WAS4KayhXTRyDwdKKlvC7LcYtTG09GT8X4sBlMwktmrPsbA+chiPmRNM7fGRyH+Ss8/8PY9xm0IqYKyrELFL9CTUEXFqrI5/TCmwh1cIwjLKevQ="
  - secure: "CncTT2DzeIVVafDxDUINoFE+XW4KKvM/BjSvlkwdyJ7okhK/lBNmRY3hdKkk/cUH8I1UaVXM2qzLgmIDi43zLcTDnW2xWH42KysDsrKcjFTTJEz3WsmGyJh7GJZa9QPZEKrcZnYB7yjp3PCqznZL5fwULuq5j8jJ9GNhy2rEk/9q9rEfqfGLtKEnpLiyaI1DxrJUINkBxschttqL2PlocMENmCneVVPdUPJ5CF8dPYthmllq8wAoxpCqDkcHmHAbKP2DcsTBd1jjXMjFKvOrXMyi9lIcTAOc9NtU3dVGS3Zva5MuaqoLyjPHhfQqWsynM+Ryq9Qms5LFBUCaEWewofG+4OWIT8YOei2V5quWSNhM1qMl5UkBo99eYLwSHChGqsHgzq0HQPR/XOrmEVyrYsV+4IlujuWTrNoksuvT0zBtZVvAjiDrVoD83fxbkagKwroj32CXcCDVpTkZQn6kNtJQJ6+keEJP8TDTzPxl/cERIoadQi2Zxx8jn2OHdKVjw3BYSn0cwMIIsssRRxYtilb39djfakTrSTtoqBknS5SnGx/hgqCa5Mg3E9GKXaAtb9QLK6Lqqp7uDVopXsGq81EdZf7U+qzIKS0cprJ9vkh6J/6rGwIOlsai51IDBKHCPwiJ0yjACjfXbID3lR69JIUAmxqWdhqOIXsknV0+81k="

cache:
  directories:
  - "$HOME/.m2"

install: mvn clean install -DskipTests=true -V -U
script: mvn test

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_ab84759248f7_key -iv $encrypted_ab84759248f7_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi